server:
  port: 8090
logging:
  level:
    root: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          custom-provider:
            clientId: custom-provider-clientId
            clientSecret: custom-provider-clientSecret
            scope:
              - openid
              - phone
              - roles
              - profile
              - user_attributes
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/callback-uri
          google:
            clientId: google-clientId
            clientSecret: google-clientSecret
        provider:
          custom-provider:
            authorization-uri: https://xxxxxxxxxxxxxx.com/oauth/authorize
            token-uri: https://xxxxxxxxxxxxxx.com/oauth/token
            user-info-uri: https://xxxxxxxxxxxxxx.com/userinfo
#            user-name-attribute: name
#            user-info-authentication-method: header
#            jwk-set-uri: https://xxxxxxxxxxxxxx.com/jwks/

